apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jump-app
  description: |
    Jump App Application
  links:
    - title: Website
      url: http://backstage.io
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    argocd/app-name: jump-app
spec:
  type: service
  lifecycle: production
  owner: user:default/guest
