apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app02-jump-app
  annotations:
    argocd/app-name: app02-jump-app
    backstage.io/kubernetes-id: app02
    backstage.io/kubernetes-namespace: jump-app
    backstage.io/source-location: url:https://github.com/acidonper/jump-app-gitops/new/feature/jump-app-dev
    backstage.io/techdocs-ref: url:https://github.com/acidonper/jump-app-gitops/new/feature/jump-app-dev
  tags:
    - microservices
    - jumpapp
spec:
  type: service
  lifecycle: production
  owner: user:guest
  providesApis:
    - "jump-app-backend"

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "jump-app-backend"
  description: "Jump App Golang Backend API"
spec:
  type: openapi
  lifecycle: production
  owner: "user:guest"
  definition:
    $text: ./openapi.yaml
